In [1]:
import sys

import tensorflow.keras
import pandas as pd

import tensorflow as tf
import numpy as np
import os
import keras

from tensorflow import data as tf_data
from keras import layers

import platform

In [2]:
model = keras.saving.load_model("stats_model_1.keras")

2024-12-17 11:45:35.096229: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-12-17 11:45:35.096268: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-12-17 11:45:35.096277: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-12-17 11:45:35.096297: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-12-17 11:45:35.096311: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

Reading in the datafile.

In [3]:
data = pd.read_csv('input.csv')

Prepare the data

In [4]:
prefix = ['mean', 'var', "skewness", 'fnn', 'pearson']



image = data.iloc[:, (56):(56+2500)]
stats = data.filter(regex='|'.join(f'^{x}' for x in prefix)).dropna(how='all')

In [5]:
image

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V2491,V2492,V2493,V2494,V2495,V2496,V2497,V2498,V2499,V2500
0,0,0,0,0,0,0,0,0,0,0.000359,...,0,0,0,0,0,0,0,0,0,0

In [6]:
stats

,mean_1,var_1,skewness_1,mean_2,var_2,skewness_2,mean_3,var_3,skewness_3,mean_4,...,var_16,skewness_16,mean_17,var_17,skewness_17,mean_18,var_18,skewness_18,pearson,fnn
0,0.237945,0.009489,0.864084,0.243297,0.023824,1.684356,0.302031,0.019527,1.181524,0.308469,...,0.055637,-0.131844,0.280938,0.009006,-0.281911,0.5,0,0,0.368133,0.435488

In [7]:
image = image.to_numpy()
image = image.reshape(1, 50, 50, 1)
stats = stats.to_numpy()
stats = stats.reshape(1, 56)

Make predictions.

In [8]:
predictions = model.predict(stats)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

2024-12-17 11:46:17.619232: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

In [9]:
print(predictions)

[[0.50857985]]